import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      <header style={{ padding: '10px', backgroundColor: 'hsla(var(--coolgrey-950), var(--opacity-90))', textAlign: 'center' }}>
        <h1>Path of Exile Gems</h1>
      </header>
      <main style={{ margin: '20px' }}>{children}</main>
      <footer style={{ padding: '10px', textAlign: 'center', backgroundColor: 'hsla(var(--coolgrey-950), var(--opacity-90))' }}>
        <p>© 2024 Path of Exile Gems Viewer</p>
      </footer>
    </body>
  </html>
  );
}
