import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      <header className="flex shadow-md py-4 px-4 sm:px-10 bg-slate-800 font-[sans-serif] min-h-70 tracking-wide relative z-50">
        <h1 className="text-2xl">Path of Exile Gems</h1>
        
      </header>
      <main style={{ margin: '20px' }}>{children}</main>
      <footer style={{ padding: '10px', textAlign: 'center' }}>
        <p>© 2024 Path of Exile Gems Viewer</p>
      </footer>
    </body>
  </html>
  );
}
